[package]
name = "media-scale-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
panic-message = "0.3.0"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
chrono = "0.4.39"
notify = "6.1.1"