name: nas-rom-manager

services:
  nrm-server:
    container_name: nrm-server
    command: ['/nrm-server']
    image: nrm-server:latest
    build:
      context: ../server
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - /YOUR/NRM/CONFIG/PATH:/config/NRM
      - /YOUR/LIBRARY/PATH:/library
    env_file:
      - .env
    environment:
      NRM_GRIDS_CACHE_DIR: /config/NRM/covers
      NRM_CONFIG_DIR: /config/NRM/config
      NRM_PARSERS_DIR: /config/NRM/parsers
      RUST_LOG: info
      NRM_DEBUG: false
    ports:
      - 1500:1500
    healthcheck:
      disable: false

  nrm-web:
    container_name: nrm-web
    image: nrm-web:latest
    # Needed for rootless docker setup, see https://github.com/moby/moby/issues/45919
    # user: 0:0
    build:
      context: ../web
      dockerfile: ./Dockerfile
    command: ['/nrm-web']
    env_file:
      - .env
    environment:
      INJECTION_ENV_PREFIX: RUNTIME_
      RUNTIME_SERVER_URL: 127.0.0.1:1500
      # TODO: calculate these at build time
      RUNTIME_BUILD_DATE: "March 11th, 2025"
      RUNTIME_APP_VERSION: "1.0.0"
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - nrm-server